### ISSUE TITLE
Enhance 404 error page

### ISSUE THREAD

**Issue by ho-thach-nguyen-lx** [ilBury/FreestyleApp#4]
It's better to remove "Here description goes" from the page or add some useful text something like "Please check whether the url is correct" or add button "Go to home page"

<img width="1439" alt="Screenshot 2024-03-06 alle 10 30 26" src="https://github.com/ilBury/FreestyleApp/assets/160735908/bc561bb2-43e2-4758-a010-0230665f0173">

**Comment by ilBury** [comment]
Was corrected
